// Playbook sections for the CEO dashboard. Regenerate from marketing/PLAYBOOK.md. Not a route.
module.exports = [
  {
    id: 'the-machine',
    title: 'The machine (funnel at a glance)',
    icon: '⚙️',
    html: '<pre><code>F5Bot email alert → triage (2 min) → public comment (value, no link) → DM ~30 min later (the read)\n→ they reply → send 2 relevant examples → preview-first offer → watermarked preview → they approve\n→ Stripe invoice → deliver clean files → ask for testimonial + referral</code></pre>\n<p>Money never moves before a preview exists. Files never go out clean before money moves.</p>',
    text: 'The machine (funnel at a glance)\nF5Bot email alert → triage (2 min) → public comment (value, no link) → DM ~30 min later (the read) → they reply → send 2 relevant examples → preview-first offer → watermarked preview → they approve → Stripe invoice → deliver clean files → ask for testimonial + referral\nMoney never moves before a preview exists. Files never go out clean before money moves.'
  },
  {
    id: 'what-to-do-based-on-where-the-person-is',
    title: 'What to do based on where the person is',
    icon: '🎯',
    html: '<table>\n<thead><tr><th>Signal (what the post says)</th><th>Temperature</th><th>Play</th></tr></thead>\n<tbody>\n<tr><td>"Looking to hire / need an explainer video"</td><td>🔥 Buyer</td><td>Skip the comment. DM directly with portfolio link + 1 question about their product. Price OK if they ask or if the post is about price.</td></tr>\n<tr><td>"Narrowed it down to N companies / comparing vendors"</td><td>🔥 Buyer</td><td>Comment with a useful how-to-choose criterion (no self-mention), DM after with examples. Never trash the competitors.</td></tr>\n<tr><td>"About to spend $X on video / is it worth it"</td><td>🔥 Buyer w/ doubt</td><td>Agree with their doubt honestly. Video amplifies a message, it can\'t fix positioning. Then the cheap-test framing. Price contrast belongs in the DM here.</td></tr>\n<tr><td>"Roast my landing page / website"</td><td>🌡 Warm</td><td>Run <code>npm run pitch &lt;url&gt;</code>. Comment a SHORT version of the read (&lt;120 words, no link). DM the full read 30 min later.</td></tr>\n<tr><td>"Traffic but no signups / conversions"</td><td>🌡 Warm</td><td>Same as roast, but lead with one concrete conversion observation, not the video.</td></tr>\n<tr><td>Describes the exact pain (onboarding, churn, can\'t explain product)</td><td>🌡 Warm</td><td>Value comment answering the actual question. DM only if they engage.</td></tr>\n<tr><td>Competitor self-promo / other freelancers bidding</td><td>🧊 Intel</td><td>Read what they pitch and what gets replies. Never engage. Log anything notable.</td></tr>\n<tr><td>AI-tool builders (doc-to-video etc.)</td><td>🧊 Intel</td><td>Competitor watch only. Their existence = the "studio look without studio price" wedge gets stronger.</td></tr>\n</tbody>\n</table>',
    text: 'What to do based on where the person is\nSignal (what the post says) | Temperature | Play\n"Looking to hire / need an explainer video" | 🔥 Buyer | Skip the comment. DM directly with portfolio link + 1 question about their product. Price OK if they ask or if the post is about price.\n"Narrowed it down to N companies / comparing vendors" | 🔥 Buyer | Comment with a useful how-to-choose criterion (no self-mention), DM after with examples. Never trash the competitors.\n"About to spend $X on video / is it worth it" | 🔥 Buyer w/ doubt | Agree with their doubt honestly. Video amplifies a message, it can\'t fix positioning. Then the cheap-test framing. Price contrast belongs in the DM here.\n"Roast my landing page / website" | 🌡 Warm | Run npm run pitch <url>. Comment a SHORT version of the read (<120 words, no link). DM the full read 30 min later.\n"Traffic but no signups / conversions" | 🌡 Warm | Same as roast, but lead with one concrete conversion observation, not the video.\nDescribes the exact pain (onboarding, churn, can\'t explain product) | 🌡 Warm | Value comment answering the actual question. DM only if they engage.\nCompetitor self-promo / other freelancers bidding | 🧊 Intel | Read what they pitch and what gets replies. Never engage. Log anything notable.\nAI-tool builders (doc-to-video etc.) | 🧊 Intel | Competitor watch only. Their existence = the "studio look without studio price" wedge gets stronger.'
  },
  {
    id: 'dm-value-order',
    title: 'DM value order (never shuffle)',
    icon: '💬',
    html: '<ol>\n<li><strong>Proof you looked</strong> — quote their actual headline / name their actual art. One sentence.</li>\n<li><strong>Genuine compliment</strong> — specific, real. If the site is good, say so plainly.</li>\n<li><strong>One real non-video fix</strong> — free help unrelated to the service (their broken hero image, the domain, a heading cut). This is what earns the pitch.</li>\n<li><strong>The angle</strong> — the ONE true observation (art decorates but doesn\'t explain / format fights the customer / pre-launch means the site IS the demo / invisible product needs motion).</li>\n<li><strong>Soft offer</strong> — starts at "happy to show you a couple examples." Existing examples only, never a free custom sample.</li>\n</ol>\n<p><strong>Price rules:</strong> never in a first DM, except when the post itself is about price/budget (then $900 flat vs $5k–15k studio contrast is the differentiator). Founding preview-first offer: $250, pay only on approving the watermarked preview, testimonial trade. Ladder: $49 audit (credited) → $150 rewrite → $350 page → $900 video.</p>',
    text: 'DM value order (never shuffle)\n1. Proof you looked — quote their actual headline / name their actual art. One sentence.\n2. Genuine compliment — specific, real. If the site is good, say so plainly.\n3. One real non-video fix — free help unrelated to the service (their broken hero image, the domain, a heading cut). This is what earns the pitch.\n4. The angle — the ONE true observation (art decorates but doesn\'t explain / format fights the customer / pre-launch means the site IS the demo / invisible product needs motion).\n5. Soft offer — starts at "happy to show you a couple examples." Existing examples only, never a free custom sample.\nPrice rules: never in a first DM, except when the post itself is about price/budget (then $900 flat vs $5k–15k studio contrast is the differentiator). Founding preview-first offer: $250, pay only on approving the watermarked preview, testimonial trade. Ladder: $49 audit (credited) → $150 rewrite → $350 page → $900 video.'
  },
  {
    id: 'voice-rules',
    title: 'Voice rules (updated from live Reddit feedback)',
    icon: '🗣️',
    html: '<ul>\n<li><strong>Human-loose case, not machine-perfect.</strong> Both extremes read as AI: flawless sentence case = ChatGPT, forced all-lowercase got publicly clocked ("ChatGPT, don\'t use capital letters so it looks like a human wrote it"). So MIX it: capitalize most sentence starts and "I", but let a couple go lowercase. Bake in ~one small natural slip every few sentences (dropped apostrophe like "dont/youre", a missing capital, an unclosed paren, a minor typo) and casual contractions (gonna, gotta, kinda, tbh). Enough to read "sharp person on their phone," never "can\'t write."</li>\n<li><strong>No em dashes. Ever.</strong> Periods, commas, parentheses.</li>\n<li><strong>Never name another vendor or agency</strong>, even positively. It reads as astroturfing for them ("stealth promotion for that one company").</li>\n<li><strong>One clever line max per message.</strong> If every sentence is quotable, a model wrote it. Most sentences should be plain.</li>\n<li>No "disclosure:" openers, no "here\'s the thing", no "it\'s not X, it\'s Y" more than once, no tidy three-item lists.</li>\n<li>Public comments: under ~120 words. DMs can breathe.</li>\n<li>Honesty is the engine: if a site passes the 7-second test, say it passes. Never manufacture a problem.</li>\n</ul>',
    text: 'Voice rules (updated from live Reddit feedback)\nHuman-loose case, not machine-perfect. Both extremes read as AI: flawless sentence case = ChatGPT, forced all-lowercase got publicly clocked ("ChatGPT, don\'t use capital letters so it looks like a human wrote it"). So MIX it: capitalize most sentence starts and "I", but let a couple go lowercase. Bake in ~one small natural slip every few sentences (dropped apostrophe like "dont/youre", a missing capital, an unclosed paren, a minor typo) and casual contractions (gonna, gotta, kinda, tbh). Enough to read "sharp person on their phone," never "can\'t write."\nNo em dashes. Ever. Periods, commas, parentheses.\nNever name another vendor or agency, even positively. It reads as astroturfing for them ("stealth promotion for that one company").\nOne clever line max per message. If every sentence is quotable, a model wrote it. Most sentences should be plain.\nNo "disclosure:" openers, no "here\'s the thing", no "it\'s not X, it\'s Y" more than once, no tidy three-item lists.\nPublic comments: under ~120 words. DMs can breathe.\nHonesty is the engine: if a site passes the 7-second test, say it passes. Never manufacture a problem.'
  },
  {
    id: 'tools',
    title: 'Tools (what generates what)',
    icon: '🛠️',
    html: '<table>\n<thead><tr><th>Command</th><th>Produces</th></tr></thead>\n<tbody>\n<tr><td><code>npm run pitch &lt;url&gt;</code></td><td>Homepage read + DM (full + short) → <code>marketing/reads/&lt;domain&gt;.md</code></td></tr>\n<tr><td><code>npm run audit &lt;url&gt;</code></td><td>$49 audit deliverable</td></tr>\n<tr><td><code>npm run script &lt;id&gt;</code> → <code>npm run process &lt;id&gt; [--draft]</code></td><td>Script → full video per aspect in <code>projects/&lt;id&gt;/output</code></td></tr>\n<tr><td><code>npm run youtube:upload &lt;id&gt;</code></td><td>Unlisted upload for client review links</td></tr>\n<tr><td>Codex CLI (see memory)</td><td>Second-opinion frame QA, screenshot→SVG asset stylizing. Uses ChatGPT quota, keep prompts small.</td></tr>\n</tbody>\n</table>',
    text: 'Tools (what generates what)\nCommand | Produces\nnpm run pitch <url> | Homepage read + DM (full + short) → marketing/reads/<domain>.md\nnpm run audit <url> | $49 audit deliverable\nnpm run script <id> → npm run process <id> [--draft] | Script → full video per aspect in projects/<id>/output\nnpm run youtube:upload <id> | Unlisted upload for client review links\nCodex CLI (see memory) | Second-opinion frame QA, screenshot→SVG asset stylizing. Uses ChatGPT quota, keep prompts small.'
  },
  {
    id: 'f5bot-keyword-list',
    title: 'F5Bot keyword list (paste into f5bot.com dashboard — matches are whole-word, case-insensitive)',
    icon: '🔑',
    html: '<p>The pain-signal phrases out-convert the "explainer video" ones (those are mostly other freelancers advertising). Tier by what\'s actually worked.</p>\n<h4>Tier 1 — warm pain (the goldmine, keep all):</h4>\n<p><code>traffic but no</code> · <code>isn\'t converting</code> · <code>not converting</code> · <code>no signups</code> · <code>low conversion</code> · <code>roast my landing page</code> · <code>roast my website</code> · <code>roast my startup</code> · <code>roast my saas</code> · <code>website feedback</code> · <code>landing page feedback</code> · <code>homepage feedback</code></p>\n<h4>Tier 2 — add these (same intent, MARKETING-context only so they stay clean):</h4>\n<p><code>bounce rate</code> · <code>high bounce</code> · <code>visitors but no</code> · <code>clicks but no</code> · <code>signups are low</code> · <code>confusing landing</code> · <code>brutal feedback on</code> · <code>feedback on my landing</code> · <code>feedback on my site</code></p>\n<h4>Tier 3 — buyer-intent (rarer, higher value when they hit):</h4>\n<p><code>explainer video</code> · <code>product demo video</code> · <code>demo video</code> · <code>need an animator</code> · <code>looking for a video editor</code> · <code>product video</code> · <code>onboarding video</code> · <code>sales video</code></p>\n<h4>❌ REMOVE / never add (2026-07-04, learned the hard way):</h4>\n<p><code>hard to explain</code>, <code>people don\'t get</code>, <code>nobody understands</code>, <code>struggling to explain</code>, <code>explain what we do</code>, <code>explain my product</code>. These are EVERYDAY ENGLISH, not SaaS pain. In one afternoon <code>hard to explain</code> pulled climbing shoes, newborns, a Strokes football sim, astral projection, and NBA contracts, hit its 50-hits/day cap, and F5Bot auto-disabled it. <code>people don\'t get</code> / <code>nobody understands</code> pulled r/rant and r/askteddit profanity. The lesson: a keyword must be inherently PRODUCT/MARKETING context (conversion, signups, landing page, roast, bounce) — a phrase people use in normal conversation is unminable no matter how well it describes the pain, because F5Bot has no boolean AND to add "…about a SaaS."</p>\n<p>Note: F5Bot matches the phrase as a whole-word substring, so keep phrases 2-3 words (a 1-word keyword like "explainer" floods you). It also caps each keyword at 50 hits/24h then auto-disables it, so a noisy keyword also BURNS your good ones\' attention. Prune any keyword returning &gt;50% noise in a day.</p>',
    text: 'F5Bot keyword list (paste into f5bot.com dashboard — matches are whole-word, case-insensitive)\nThe pain-signal phrases out-convert the "explainer video" ones (those are mostly other freelancers advertising). Tier by what\'s actually worked.\nTier 1 — warm pain (the goldmine, keep all): traffic but no · isn\'t converting · not converting · no signups · low conversion · roast my landing page · roast my website · roast my startup · roast my saas · website feedback · landing page feedback · homepage feedback\nTier 2 — add these (same intent, MARKETING-context only so they stay clean): bounce rate · high bounce · visitors but no · clicks but no · signups are low · confusing landing · brutal feedback on · feedback on my landing · feedback on my site\nTier 3 — buyer-intent (rarer, higher value when they hit): explainer video · product demo video · demo video · need an animator · looking for a video editor · product video · onboarding video · sales video\n❌ REMOVE / never add (2026-07-04, learned the hard way): hard to explain, people don\'t get, nobody understands, struggling to explain, explain what we do, explain my product. These are EVERYDAY ENGLISH, not SaaS pain. In one afternoon hard to explain pulled climbing shoes, newborns, a Strokes football sim, astral projection, and NBA contracts, hit its 50-hits/day cap, and F5Bot auto-disabled it. people don\'t get / nobody understands pulled r/rant and r/askteddit profanity. The lesson: a keyword must be inherently PRODUCT/MARKETING context (conversion, signups, landing page, roast, bounce) — a phrase people use in normal conversation is unminable no matter how well it describes the pain, because F5Bot has no boolean AND to add "…about a SaaS."\nNote: F5Bot matches the phrase as a whole-word substring, so keep phrases 2-3 words (a 1-word keyword like "explainer" floods you). It also caps each keyword at 50 hits/24h then auto-disables it, so a noisy keyword also BURNS your good ones\' attention. Prune any keyword returning >50% noise in a day.'
  },
  {
    id: 'standing-rules',
    title: 'Standing rules',
    icon: '📋',
    html: '<ul>\n<li>Watermark every preview until paid. Stripe invoice only. No overpayment "buyers", no WhatsApp moves, no shipping-agent stories (ArtStation scam pattern).</li>\n<li>F5Bot emails: triage → act on the good ones → DELETE all of them (Trash, same day).</li>\n<li>Client examples: send the onwave showcase + one brand-matched sample closest to their space.</li>\n<li>One video = one message. If a prospect\'s positioning is broken, say so before selling motion.</li>\n<li>Dead outreach addresses so far: techspy.pro, passportreader.com (both bounced permanently).</li>\n</ul>',
    text: 'Standing rules\nWatermark every preview until paid. Stripe invoice only. No overpayment "buyers", no WhatsApp moves, no shipping-agent stories (ArtStation scam pattern).\nF5Bot emails: triage → act on the good ones → DELETE all of them (Trash, same day).\nClient examples: send the onwave showcase + one brand-matched sample closest to their space.\nOne video = one message. If a prospect\'s positioning is broken, say so before selling motion.\nDead outreach addresses so far: techspy.pro, passportreader.com (both bounced permanently).'
  },
  {
    id: 'red-flag-log',
    title: 'Red-flag log (things that burned us, never repeat)',
    icon: '🚩',
    html: '<ul>\n<li>All-lowercase voice → flagged as AI (r/ProductMarketing, 2026-07-04).</li>\n<li>Naming a vendor positively → flagged as stealth promo (same thread).</li>\n<li>Em dashes → flagged as AI (earlier client feedback).</li>\n<li>Long polished public comments → downvote bait. Short in public, depth in DM.</li>\n<li>Fake portfolio links → never. Real work only (this is why the ArtStation portfolio exists).</li>\n</ul>',
    text: 'Red-flag log (things that burned us, never repeat)\nAll-lowercase voice → flagged as AI (r/ProductMarketing, 2026-07-04).\nNaming a vendor positively → flagged as stealth promo (same thread).\nEm dashes → flagged as AI (earlier client feedback).\nLong polished public comments → downvote bait. Short in public, depth in DM.\nFake portfolio links → never. Real work only (this is why the ArtStation portfolio exists).'
  }
];
